[changelog]
header = """
# Changelog
"""

body = """
{% macro print_commit(commit) -%}
    - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
        {% if commit.breaking %}[**breaking**] {% endif %}\
        {{ commit.message | split(pat="\n") | first | upper_first }} \
        {% if commit.remote.username %} @{{ commit.remote.username }}{% else %} {{ commit.author.name }}{% endif %}
        {%- if commit.footers -%}
            {%- for footer in commit.footers -%}
                {%- if footer.token == "Co-authored-by" -%}
                    {%- set co_author_name = footer.value | split(pat=" <") | first | trim %} @{{ co_author_name }}
                {%- endif -%}
            {%- endfor -%}
        {%- endif %}
{% endmacro -%}

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits | filter(attribute="scope") | sort(attribute="scope") %}
        {{ self::print_commit(commit=commit) }}
    {%- endfor %}
    {% for commit in commits %}
        {%- if not commit.scope -%}
            {{ self::print_commit(commit=commit) }}
        {% endif -%}
    {% endfor -%}
{% endfor -%}
"""

footer = """
{%- set base_url = "https://github.com/" ~ remote.github.owner ~ "/" ~ remote.github.repo -%}
{%- set compare = previous.version ~ "..." ~ version -%}
Full Changelog: [{{ compare }}]({{ base_url }}/compare/{{ compare }})
"""

[git]
filter_unconventional = false
skip_merges = true
commit_parsers = [
    { message = "^feat", group = "✨ Features" },
    { message = "^fix", group = "🐛 Bug Fixes" },
    { message = "^docs", group = "📚 Documentation" },
    { message = "^perf", group = "🚀 Performance" },
    { message = "^refactor", group = "🚜 Refactor" },
    { message = "^test", group = "🧪 Testing" },
    { message = "^ci", group = "⚙️ CI" },
    { message = "^chore", group = "🔧 Chore" },
    { message = "^chore\\(deps\\)", group = "📦 Dependencies" },
    { message = "^build", group = "🏗️ Build" },
    { message = ".*", group = "💼 Other" },
]

[remote.github]
owner = "Embracing-Galaxy"
repo = "lx-music-sync-server-rs"
