[package]
name = "lx-music-sync-server"
version = "0.1.0"
edition = "2024"

[dependencies]
log = { version = "0.4", features = ["max_level_debug", "release_max_level_info"] }
env_logger = "0.11"
paste = "1.0"

rand = "^0.10"
openssl = "0.10"
base64 = "0.22"
flate2 = "1.1"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

dashmap = "6"
arc-swap = { version = "^1.7.1", features = ["serde"] }
futures-util = "0.3"
tokio = { version = "1.47", features = ["fs", "macros", "rt-multi-thread", "time"] }
axum = { version = "0.8", default-features = false, features = ["http1", "tokio", "query", "http2", "ws"] }

[lints.clippy]
unused_async = "warn"