name: Release
run-name: Release ${{ github.ref_name }}

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  generate-changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: cliff
        with:
          config: .github/cliff.toml
          args: --latest --strip header
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            setup: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config

          - target: x86_64-unknown-linux-musl
            container:
              image: rust:alpine
            setup: apk add --no-cache openssl-dev musl-dev pkgconfig

    runs-on: ubuntu-latest
    container: ${{ matrix.container }}

    env:
      CARGO_HOME: ${{ github.workspace }}/.cargo #set for container

    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@stable
        if: ${{ !matrix.container }}
        with:
          targets: ${{ matrix.target }}

      - name: Install system dependencies
        run: ${{ matrix.setup }}

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Build
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: lx-music-sync-server-${{ matrix.target }}
          path: target/release/lx-music-sync-server
          archive: false

  release:
    needs: [ generate-changelog, build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: lx-music-sync-server-*

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          body: ${{ needs.generate-changelog.outputs.release_body }}
          prerelease: ${{ contains(github.ref_name, 'beta') }}
          files: |
            lx-music-sync-server-*
